Repository autobrr/omegabrr, pull requests merged in 2023-01, with the labels that each got.

#17 feat(autobrr): support basic auth
  README.md
  internal/processor/radarr.go
  internal/processor/service.go
  internal/processor/sonarr.go
  pkg/autobrr/client.go
Labels: enhancement

#18 feat(arr): add readarr and lidarr support
  internal/domain/config.go
  internal/processor/lidarr.go
  internal/processor/readarr.go
  internal/processor/service.go
Labels: enhancement

#19 docs: add lidarr and readarr to example config
  README.md
Labels: documentation

#21 fix: dont exit on error during initial processing
  cmd/omegabrr/main.go
Labels: bug, enhancement

#20 feat: Use TV/Movies/Album by default
  README.md
  config.yml
  internal/domain/config.go
  internal/processor/lidarr.go
  internal/processor/radarr.go
  internal/processor/readarr.go
  internal/processor/sonarr.go
  internal/processor/title.go
  pkg/autobrr/client.go
Labels: enhancement

#22 build: update goreleaser action version
  .github/workflows/build.yaml
Labels: enhancement, build

#23 fix(config): change default
  cmd/omegabrr/main.go
  internal/domain/config.go
Labels: enhancement

#24 docs: add systemd unit example
  README.md
  distrib/systemd/omegabrr@.service
Labels: documentation

#25 build: correct release flag arg
  .github/workflows/build.yaml
Labels: bug, build
