Repository autobrr/omegabrr, pull requests merged in 2023-02, with the labels that each got.

#26 fix(readme): autobrr occurences to omegabrr
  README.md
Labels: documentation

#29 feat: Do not clear match_releases when using shows
  pkg/autobrr/client.go
Labels: enhancement

#31 feat(arr): add Whisparr
  README.md
  config.yml
  internal/domain/config.go
  internal/processor/service.go
Labels: enhancement

#32 feat(sonarr): Include alternate titles
  README.md
  internal/domain/config.go
  internal/processor/sonarr.go
Labels: enhancement

#33 fix(config): fixed typo in configTemplate
  internal/domain/config.go
Labels: documentation

#34 fix(config): removed tabs in config
  internal/domain/config.go
Labels: bug

#36 fix(config) fixed bad indentations
  internal/domain/config.go
Labels: bug

#37 enhancement(titles): improved parsing
  go.mod
  go.sum
  internal/processor/title.go
  internal/processor/title_test.go
Labels: enhancement

#38 feat(generate-token): optional API token length
  README.md
  cmd/omegabrr/main.go
  go.mod
  internal/apitoken/token.go
  internal/domain/config.go
Labels: enhancement
